<?php

  function movie_reservations_theme($existing, $type, $theme, $path) {   

    return array(
      'movie_reservations' => 
       array('variables' =>
       array('movies' =>array(), 'title' => '')));    
  }

    /*
       $f =  drupal_get_form('example_module_form', $node);
        $node->content['data_collection_form'] = array('#value' => $f, '#weight' => 1); 

        movie_theme_hook' => [
            'render element' => 'children',
            
            'template' => 'movie-theme-hook',
            
            'path' => $path . '/templates',
            ]

             return ;
    */
