_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 5291dd1f-eae5-4e9f-8a5e-7fb240d3f70f
name: Bioskop
mail: bioskop@bioskop.rs
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
